### ISSUE TITLE
功能需求: 实现rt_hw_us_delay

### ISSUE THREAD

**Issue by wendal** [RT-Thread/W601_IoT_Board#10]
rtt的ds18b20/dht11等基于单总线协议的package, 均使用rt_hw_us_delay进行us级延时

当前没有w60x官方实现的rt_hw_us_delay, 所以会回落到RT_WEAK默认实现, 也就是基于stm32的实现, 编译时必然报错.

希望能提供rt_hw_us_delay的官方实现

**Comment by wendal** [comment]
在 drv_soft_i2c.c里面有个w60x_udelay实现方法

**Comment by armink** [comment]
方便给 rt-thread/w60x BSP 提交一个 pr 吗？

**Comment by wendal** [comment]
好的, 我试试

**Comment by wendal** [comment]
已提交pr https://github.com/RT-Thread/rt-thread/pull/3359

**Comment by armink** [comment]
👍
