### ISSUE TITLE
w600运行此sdk无法使用WiFi

### ISSUE THREAD

**Issue by xupenghu** [RT-Thread/W601_IoT_Board#8]
使用的是星通智联的TW-03模组，运行16_iot_wifi_manager例程时不停重启，已经更改过rtconfig.h里面的宏为#define SOC_W600_A8xx

**Comment by armink** [comment]
看下 docs 下的 UM3106 说明 [《UM3106-RT-Thread-基于W600 芯片的例程使用说明.pdf》](https://github.com/RT-Thread/W601_IoT_Board/blob/master/docs/UM3106-RT-Thread-%E5%9F%BA%E4%BA%8EW600%20%E8%8A%AF%E7%89%87%E7%9A%84%E4%BE%8B%E7%A8%8B%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.pdf)

**Comment by xupenghu** [comment]
看过这个文档了，里面的注意点也都确认过的。这个是重启的log

msh />
msh />
msh />wifi scan
[D/WLAN.mgnt] L:1757 rt_wlan_scan_with_info is run
[SFUD]Warning: Read SFDP parameter header information failed. The norflash is not support JEDEC SFDP.
[SFUD]Warning: This flash device is not found or not support.
[SFUD]Warning: Read SFDP parameter header information failed. The norflash is not support JEDEC SFDP.
[SFUD]Warning: This flash device is not found or not support.
[SFUD]Error: norflash flash device is initialize fail.
[I/FAL] RT-Thread Flash Abstraction Layer (V0.4.0) initialize success.
[E/OTA] (ota_main:41) download partition is not exist, please check your configuration!
[D/OTA] (ota_main:105) jump to APP!
redirect_addr:8010100, stk_addr:20002A80, len:851968

 \ | /
- RT -     Thread Operating System
 / | \     4.0.2 build 16:23:12 Oct  6 2019
 2006 - 2019 Copyright by rt-thread team
The current version of APP firmware is 2.0.1
The current version of HW is 1.0.1

lwIP-2.0.2 initialized!
[SFUD] Find a Winbond flash chip. Size is 16777216 bytes.
[SFUD] w25q128 flash device is initialize success.
[I/sal.skt] Socket Abstraction Layer initialize success.
[I/FAL] RT-Thread Flash Abstraction Layer (V0.3.0) initialize success.
[I/FAL] The FAL block device (filesystem) created successfully
[I/main] Filesystem initialized!
[Flash] EasyFlash V3.3.0 is initialize success.
[Flash] You can get the latest version on https://github.com/armink/EasyFlash .
[D/WLAN.mgnt] L:1925 rt_wlan_register_event_handler is run event:0
[D/WLAN.mgnt] L:824 rt_wlan_set_mode is run dev_name:wlan0 mode:STA
[I/WLAN.dev] wlan init success
[I/WLAN.lwip] eth device init ok name:w0
[D/main] start to autoconnect ...
[D/WLAN.mgnt] L:1685 rt_wlan_config_autoreconnect is run enable:0
msh />[I/audio_thread] audio thread init success.
[D/main] <===============================================>
[I/main] The system now boot 83 times
[I/main] The current version of APP firmware is 2.0.1
[I/main] The current version of HW is 1.0.1
[D/main] <===============================================>

**Comment by xupenghu** [comment]
rtt的boot loader是闭源的 所有刚上电打印的错误是没法找到flash，所以无法使用rtt的ota功能，这个如果希望更改spi管脚和flash容量，是不是需要联系你们定制，感觉不够灵活.........

**Comment by armink** [comment]
跟星通智联沟通了下，你这个问题可能是：**电源问题，还有就是需要擦除**

**Comment by armink** [comment]
W600 的 OTA 是可以用的，但是得更换分区表，看下这个： [RT-Thread 带 OTA 1M 分区表 20191008.zip](https://github.com/RT-Thread/W601_IoT_Board/files/3705518/RT-Thread.OTA.1M.20191008.zip)

**Comment by xupenghu** [comment]
谢谢龙哥 重启确实是电源问题，之前的LDO带载能力太弱，换了新的就不重启了。看了这个分区表，使用w600片内flash确实不需要更改boot loader了 但是app固件大小有了限制，感谢感谢
